use_frameworks!

platform :ios, '9.0'

target 'ClangTraceLaurchMethods_Example' do
  pod 'ClangTraceLaurchMethods', :path => '../'

  target 'ClangTraceLaurchMethods_Tests' do
    inherit! :search_paths

    
  end
end
